### PR TITLE
Better patch for #13, #14, #15

### PR DESCRIPTION
**Pull request by Orio91**
This one should be cleaner than  #22 :)

### CODE REVIEW

**Comment by nb** [comment]
Thanks, @rjollos, you’re right that the plugin is not maintained and thanks for forking the plugin. Let us know if there is a better way to send users your way.

**Comment by rjollos** [comment]
> Let us know if there is a better way to send users your way.

@nb Would you be willing to transfer the repository to the trac-hacks GitHub org? That way we would get all the open issues and the URL would redirect to the new location.

If yes, just let me know and I'll setup so the repository can be transferred.

**Comment by rjollos** [comment]
> @nb Would you be willing to transfer the repository to the trac-hacks GitHub org? That way we would get all the open issues and the URL would redirect to the new location.

I recall now that we discussed in #53.

**Comment by nb** [comment]
@rjollos, sure, transferring sounds good – let’s do it, let me know when you’re done with the setup and I will transfer it.

**Comment by rjollos** [comment]
Thanks! You should receive an invite to join the trac-hacks organization. Accepting will allow you to execute [these steps](https://help.github.com/articles/about-repository-transfers) and transfer the repository.

**Comment by nb** [comment]
@rjollos, unfortunately the transfer cannot be initiated, because of the https://github.com/trac-hacks/trac-code-comments-plugin-2 fork. From the docs:

> The target account must not have a repository with the same name, or a fork in the same network.

Maybe you can delete the repo on GitHub, but save the comments locally and replay them on the new remote later when we transfer it?

**Comment by rjollos** [comment]
> Maybe you can delete the repo on GitHub, but save the comments locally and replay them on the new remote later when we transfer it?

Done. Thanks for sorting that out.

**Comment by nb** [comment]
> Moving repository to `trac-hacks/trac-code-comments-plugin`. This may take a few minutes.

Thanks for the patience and for saving the project, @rjollos 🎉💯

**Pull request closed without merging**
